export const methods_0_16_4 = [
    // login_api
    "get_api_by_name",
    "get_version",
    "login",

    // follow_api
    "get_account_reputations",
    "get_blog",
    "get_blog_authors",
    "get_blog_entries",
    "get_feed",
    "get_feed_entries",
    "get_follow_count",
    "get_followers",
    "get_following",
    "get_reblogged_by",

    // database_api
    "cancel_all_subscriptions",
    "get_account_bandwidth",
    "get_account_count",
    "get_account_history",
    "get_account_references",
    "get_account_votes",
    "get_accounts",
    "get_active_categories",
    "get_active_votes",
    "get_active_witnesses",
    "get_best_categories",
    "get_block",
    "get_block_header",
    "get_chain_properties",
    "get_config",
    "get_content",
    "get_content_replies",
    "get_conversion_requests",
    "get_current_median_history_price",
    "get_discussions_by_active",
    "get_discussions_by_author_before_date",
    "get_discussions_by_blog",
    "get_discussions_by_cashout",
    "get_discussions_by_children",
    "get_discussions_by_comments",
    "get_discussions_by_created",
    "get_discussions_by_feed",
    "get_discussions_by_hot",
    "get_discussions_by_payout",
    "get_discussions_by_promoted",
    "get_discussions_by_trending",
    "get_discussions_by_votes",
    "get_dynamic_global_properties",
    "get_escrow",
    "get_feed_history",
    "get_hardfork_version",
    "get_liquidity_queue",
    "get_miner_queue",
    "get_next_scheduled_hardfork",
    "get_ops_in_block",
    "get_order_book",
    "get_open_orders",
    "get_owner_history",
    "get_potential_signatures",
    "get_recent_categories",
    "get_recovery_request",
    "get_replies_by_last_update",
    "get_required_signatures",
    "get_savings_withdraw_from",
    "get_savings_withdraw_to",
    "get_state",
    "get_tags_used_by_author",
    "get_transaction",
    "get_transaction_hex",
    "get_trending_categories",
    "get_trending_tags",
    "get_withdraw_routes",
    "get_witness_by_account",
    "get_witness_count",
    "get_witness_schedule",
    "get_witnesses",
    "get_witnesses_by_vote",
    "lookup_account_names",
    "lookup_accounts",
    "lookup_witness_accounts",
    "set_block_applied_callback",
    "set_pending_transaction_callback",
    "set_subscribe_callback",
    "verify_account_authority",
    "verify_authority",
    
    // account_by_key_api
    "get_key_references",

    // network_broadcast_api
    "broadcast_block",
    "broadcast_transaction",
    "broadcast_transaction_synchronous",
    "broadcast_transaction_with_callback",
    "set_max_block_age",

    // market_history_api
    "get_market_history",
    "get_market_history_buckets",
    // "get_order_book",
    "get_recent_trades",
    "get_ticker",
    "get_trade_history",
    "get_volume"
]
